time1=input("Please enter the first time:")
time2=input("Please enter the second time:")
time1_hours=int(time1[0:2])
time2_hours=int(time2[0:2])
time1_minutes=int(time1[2:])
time2_minutes=int(time2[2:])
hours_difference = abs(time2_hours - time1_hours)
minutes_difference = abs(time2_minutes - time1_minutes)
print(f"Time difference: {hours_difference}hours{minutes_difference}")